require('dotenv').config();
const { Pool } = require('pg');

// 800个常用日语动词数据
const verbsData = [
  // I类动词（五段动词）
  { kana: 'いく', kanji: '行く', class: 'I', meaning: '去' },
  { kana: 'くる', kanji: '来る', class: 'II', meaning: '来' },
  { kana: 'かえる', kanji: '帰る', class: 'I', meaning: '回去' },
  { kana: 'でる', kanji: '出る', class: 'II', meaning: '出去' },
  { kana: 'はいる', kanji: '入る', class: 'I', meaning: '进入' },
  { kana: 'のる', kanji: '乗る', class: 'I', meaning: '乘坐' },
  { kana: 'おりる', kanji: '降りる', class: 'II', meaning: '下车' },
  { kana: 'あるく', kanji: '歩く', class: 'I', meaning: '走路' },
  { kana: 'はしる', kanji: '走る', class: 'I', meaning: '跑' },
  { kana: 'とぶ', kanji: '飛ぶ', class: 'I', meaning: '飞' },
  { kana: 'およぐ', kanji: '泳ぐ', class: 'I', meaning: '游泳' },
  { kana: 'たつ', kanji: '立つ', class: 'I', meaning: '站立' },
  { kana: 'すわる', kanji: '座る', class: 'I', meaning: '坐' },
  { kana: 'ねる', kanji: '寝る', class: 'II', meaning: '睡觉' },
  { kana: 'おきる', kanji: '起きる', class: 'II', meaning: '起床' },
  { kana: 'たべる', kanji: '食べる', class: 'II', meaning: '吃' },
  { kana: 'のむ', kanji: '飲む', class: 'I', meaning: '喝' },
  { kana: 'つくる', kanji: '作る', class: 'I', meaning: '制作' },
  { kana: 'かう', kanji: '買う', class: 'I', meaning: '买' },
  { kana: 'うる', kanji: '売る', class: 'I', meaning: '卖' },
  { kana: 'よむ', kanji: '読む', class: 'I', meaning: '读' },
  { kana: 'かく', kanji: '書く', class: 'I', meaning: '写' },
  { kana: 'きく', kanji: '聞く', class: 'I', meaning: '听' },
  { kana: 'はなす', kanji: '話す', class: 'I', meaning: '说话' },
  { kana: 'みる', kanji: '見る', class: 'II', meaning: '看' },
  { kana: 'しる', kanji: '知る', class: 'I', meaning: '知道' },
  { kana: 'おぼえる', kanji: '覚える', class: 'II', meaning: '记住' },
  { kana: 'わすれる', kanji: '忘れる', class: 'II', meaning: '忘记' },
  { kana: 'おしえる', kanji: '教える', class: 'II', meaning: '教' },
  { kana: 'ならう', kanji: '習う', class: 'I', meaning: '学习' },
  { kana: 'べんきょうする', kanji: '勉強する', class: 'IRR', meaning: '学习' },
  { kana: 'しごとする', kanji: '仕事する', class: 'IRR', meaning: '工作' },
  { kana: 'やすむ', kanji: '休む', class: 'I', meaning: '休息' },
  { kana: 'あそぶ', kanji: '遊ぶ', class: 'I', meaning: '玩' },
  { kana: 'うたう', kanji: '歌う', class: 'I', meaning: '唱歌' },
  { kana: 'おどる', kanji: '踊る', class: 'I', meaning: '跳舞' },
  { kana: 'ひく', kanji: '弾く', class: 'I', meaning: '弹奏' },
  { kana: 'えがく', kanji: '描く', class: 'I', meaning: '画画' },
  { kana: 'とる', kanji: '撮る', class: 'I', meaning: '拍照' },
  { kana: 'あう', kanji: '会う', class: 'I', meaning: '见面' },
  { kana: 'でんわする', kanji: '電話する', class: 'IRR', meaning: '打电话' },
  { kana: 'メールする', kanji: 'メールする', class: 'IRR', meaning: '发邮件' },
  { kana: 'けっこんする', kanji: '結婚する', class: 'IRR', meaning: '结婚' },
  { kana: 'りこんする', kanji: '離婚する', class: 'IRR', meaning: '离婚' },
  { kana: 'うまれる', kanji: '生まれる', class: 'II', meaning: '出生' },
  { kana: 'しぬ', kanji: '死ぬ', class: 'I', meaning: '死' },
  { kana: 'いきる', kanji: '生きる', class: 'II', meaning: '活着' },
  { kana: 'そだつ', kanji: '育つ', class: 'I', meaning: '成长' },
  { kana: 'そだてる', kanji: '育てる', class: 'II', meaning: '养育' },
  { kana: 'あいする', kanji: '愛する', class: 'IRR', meaning: '爱' },
  { kana: 'すき', kanji: '好き', class: 'IRR', meaning: '喜欢' },
  { kana: 'きらい', kanji: '嫌い', class: 'IRR', meaning: '讨厌' },
  { kana: 'わらう', kanji: '笑う', class: 'I', meaning: '笑' },
  { kana: 'なく', kanji: '泣く', class: 'I', meaning: '哭' },
  { kana: 'おこる', kanji: '怒る', class: 'I', meaning: '生气' },
  { kana: 'よろこぶ', kanji: '喜ぶ', class: 'I', meaning: '高兴' },
  { kana: 'かなしむ', kanji: '悲しむ', class: 'I', meaning: '悲伤' },
  { kana: 'おどろく', kanji: '驚く', class: 'I', meaning: '惊讶' },
  { kana: 'しんぱいする', kanji: '心配する', class: 'IRR', meaning: '担心' },
  { kana: 'あんしんする', kanji: '安心する', class: 'IRR', meaning: '安心' },
  { kana: 'がんばる', kanji: '頑張る', class: 'I', meaning: '努力' },
  { kana: 'あきらめる', kanji: '諦める', class: 'II', meaning: '放弃' },
  { kana: 'つづける', kanji: '続ける', class: 'II', meaning: '继续' },
  { kana: 'やめる', kanji: '止める', class: 'II', meaning: '停止' },
  { kana: 'はじめる', kanji: '始める', class: 'II', meaning: '开始' },
  { kana: 'おわる', kanji: '終わる', class: 'I', meaning: '结束' },
  { kana: 'かんせいする', kanji: '完成する', class: 'IRR', meaning: '完成' },
  { kana: 'しっぱいする', kanji: '失敗する', class: 'IRR', meaning: '失败' },
  { kana: 'せいこうする', kanji: '成功する', class: 'IRR', meaning: '成功' },
  { kana: 'ちょうせんする', kanji: '挑戦する', class: 'IRR', meaning: '挑战' },
  { kana: 'どりょくする', kanji: '努力する', class: 'IRR', meaning: '努力' },
  { kana: 'れんしゅうする', kanji: '練習する', class: 'IRR', meaning: '练习' },
  { kana: 'じゅんびする', kanji: '準備する', class: 'IRR', meaning: '准备' },
  { kana: 'けいかくする', kanji: '計画する', class: 'IRR', meaning: '计划' },
  { kana: 'よやくする', kanji: '予約する', class: 'IRR', meaning: '预约' },
  { kana: 'やくそくする', kanji: '約束する', class: 'IRR', meaning: '约定' },
  { kana: 'まつ', kanji: '待つ', class: 'I', meaning: '等待' },
  { kana: 'いそぐ', kanji: '急ぐ', class: 'I', meaning: '着急' },
  { kana: 'おくれる', kanji: '遅れる', class: 'II', meaning: '迟到' },
  { kana: 'まにあう', kanji: '間に合う', class: 'I', meaning: '赶上' },
  { kana: 'つく', kanji: '着く', class: 'I', meaning: '到达' },
  { kana: 'しゅっぱつする', kanji: '出発する', class: 'IRR', meaning: '出发' },
  { kana: 'とうちゃくする', kanji: '到着する', class: 'IRR', meaning: '到达' },
  { kana: 'りょこうする', kanji: '旅行する', class: 'IRR', meaning: '旅行' },
  { kana: 'さんぽする', kanji: '散歩する', class: 'IRR', meaning: '散步' },
  { kana: 'ドライブする', kanji: 'ドライブする', class: 'IRR', meaning: '开车兜风' },
  { kana: 'うんてんする', kanji: '運転する', class: 'IRR', meaning: '驾驶' },
  { kana: 'とまる', kanji: '止まる', class: 'I', meaning: '停止' },
  { kana: 'とめる', kanji: '止める', class: 'II', meaning: '停止' },
  { kana: 'うごく', kanji: '動く', class: 'I', meaning: '移动' },
  { kana: 'うごかす', kanji: '動かす', class: 'I', meaning: '移动' },
  { kana: 'もつ', kanji: '持つ', class: 'I', meaning: '拿' },
  { kana: 'おく', kanji: '置く', class: 'I', meaning: '放置' },
  { kana: 'とる', kanji: '取る', class: 'I', meaning: '拿取' },
  { kana: 'わたす', kanji: '渡す', class: 'I', meaning: '递给' },
  { kana: 'うける', kanji: '受ける', class: 'II', meaning: '接受' },
  { kana: 'あげる', kanji: '上げる', class: 'II', meaning: '给' },
  { kana: 'もらう', kanji: 'もらう', class: 'I', meaning: '收到' },
  { kana: 'くれる', kanji: 'くれる', class: 'II', meaning: '给我' },
  { kana: 'かりる', kanji: '借りる', class: 'II', meaning: '借' },
  { kana: 'かす', kanji: '貸す', class: 'I', meaning: '借给' },
  { kana: 'かえす', kanji: '返す', class: 'I', meaning: '归还' },
  { kana: 'なくす', kanji: '無くす', class: 'I', meaning: '丢失' },
  { kana: 'みつける', kanji: '見つける', class: 'II', meaning: '找到' },
  { kana: 'さがす', kanji: '探す', class: 'I', meaning: '寻找' },
  { kana: 'みつかる', kanji: '見つかる', class: 'I', meaning: '被找到' },
  { kana: 'ひらく', kanji: '開く', class: 'I', meaning: '打开' },
  { kana: 'しめる', kanji: '閉める', class: 'II', meaning: '关闭' },
  { kana: 'あく', kanji: '開く', class: 'I', meaning: '开着' },
  { kana: 'しまる', kanji: '閉まる', class: 'I', meaning: '关着' },
  { kana: 'つける', kanji: '付ける', class: 'II', meaning: '打开' },
  { kana: 'けす', kanji: '消す', class: 'I', meaning: '关闭' },
  { kana: 'つく', kanji: '付く', class: 'I', meaning: '开着' },
  { kana: 'きえる', kanji: '消える', class: 'II', meaning: '熄灭' },
  { kana: 'でんきをつける', kanji: '電気を付ける', class: 'II', meaning: '开灯' },
  { kana: 'でんきをけす', kanji: '電気を消す', class: 'I', meaning: '关灯' },
  { kana: 'せんたくする', kanji: '洗濯する', class: 'IRR', meaning: '洗衣服' },
  { kana: 'そうじする', kanji: '掃除する', class: 'IRR', meaning: '打扫' },
  { kana: 'りょうりする', kanji: '料理する', class: 'IRR', meaning: '做饭' },
  { kana: 'あらう', kanji: '洗う', class: 'I', meaning: '洗' },
  { kana: 'ふく', kanji: '拭く', class: 'I', meaning: '擦' },
  { kana: 'きる', kanji: '切る', class: 'I', meaning: '切' },
  { kana: 'やく', kanji: '焼く', class: 'I', meaning: '烤' },
  { kana: 'にる', kanji: '煮る', class: 'II', meaning: '煮' },
  { kana: 'いためる', kanji: '炒める', class: 'II', meaning: '炒' },
  { kana: 'あじをつける', kanji: '味を付ける', class: 'II', meaning: '调味' },
  { kana: 'きる', kanji: '着る', class: 'II', meaning: '穿' },
  { kana: 'ぬぐ', kanji: '脱ぐ', class: 'I', meaning: '脱' },
  { kana: 'はく', kanji: '履く', class: 'I', meaning: '穿(下身)' },
  { kana: 'かぶる', kanji: '被る', class: 'I', meaning: '戴' },
  { kana: 'みにつける', kanji: '身に付ける', class: 'II', meaning: '佩戴' },
  { kana: 'けしょうする', kanji: '化粧する', class: 'IRR', meaning: '化妆' },
  { kana: 'かみをとかす', kanji: '髪をとかす', class: 'I', meaning: '梳头' },
  { kana: 'はをみがく', kanji: '歯を磨く', class: 'I', meaning: '刷牙' },
  { kana: 'シャワーをあびる', kanji: 'シャワーを浴びる', class: 'II', meaning: '洗澡' },
  { kana: 'おふろにはいる', kanji: 'お風呂に入る', class: 'I', meaning: '泡澡' },
  { kana: 'びょういんにいく', kanji: '病院に行く', class: 'I', meaning: '去医院' },
  { kana: 'くすりをのむ', kanji: '薬を飲む', class: 'I', meaning: '吃药' },
  { kana: 'ちゅうしゃする', kanji: '注射する', class: 'IRR', meaning: '打针' },
  { kana: 'けんさする', kanji: '検査する', class: 'IRR', meaning: '检查' },
  { kana: 'しんさつする', kanji: '診察する', class: 'IRR', meaning: '诊察' },
  { kana: 'ちりょうする', kanji: '治療する', class: 'IRR', meaning: '治疗' },
  { kana: 'かいふくする', kanji: '回復する', class: 'IRR', meaning: '恢复' },
  { kana: 'びょうきになる', kanji: '病気になる', class: 'I', meaning: '生病' },
  { kana: 'げんきになる', kanji: '元気になる', class: 'I', meaning: '康复' },
  { kana: 'かぜをひく', kanji: '風邪をひく', class: 'I', meaning: '感冒' },
  { kana: 'ねつがでる', kanji: '熱が出る', class: 'II', meaning: '发烧' },
  { kana: 'せきがでる', kanji: '咳が出る', class: 'II', meaning: '咳嗽' },
  { kana: 'あたまがいたい', kanji: '頭が痛い', class: 'IRR', meaning: '头疼' },
  { kana: 'おなかがいたい', kanji: 'お腹が痛い', class: 'IRR', meaning: '肚子疼' },
  { kana: 'けがをする', kanji: '怪我をする', class: 'IRR', meaning: '受伤' },
  { kana: 'なおる', kanji: '治る', class: 'I', meaning: '痊愈' },
  { kana: 'なおす', kanji: '治す', class: 'I', meaning: '治愈' },
  { kana: 'しゅじゅつする', kanji: '手術する', class: 'IRR', meaning: '手术' },
  { kana: 'にゅういんする', kanji: '入院する', class: 'IRR', meaning: '住院' },
  { kana: 'たいいんする', kanji: '退院する', class: 'IRR', meaning: '出院' },
  { kana: 'がっこうにいく', kanji: '学校に行く', class: 'I', meaning: '上学' },
  { kana: 'じゅぎょうをうける', kanji: '授業を受ける', class: 'II', meaning: '上课' },
  { kana: 'しけんをうける', kanji: '試験を受ける', class: 'II', meaning: '考试' },
  { kana: 'しゅくだいをする', kanji: '宿題をする', class: 'IRR', meaning: '做作业' },
  { kana: 'そつぎょうする', kanji: '卒業する', class: 'IRR', meaning: '毕业' },
  { kana: 'にゅうがくする', kanji: '入学する', class: 'IRR', meaning: '入学' },
  { kana: 'りゅうがくする', kanji: '留学する', class: 'IRR', meaning: '留学' },
  { kana: 'けんきゅうする', kanji: '研究する', class: 'IRR', meaning: '研究' },
  { kana: 'はっぴょうする', kanji: '発表する', class: 'IRR', meaning: '发表' },
  { kana: 'しつもんする', kanji: '質問する', class: 'IRR', meaning: '提问' },
  { kana: 'こたえる', kanji: '答える', class: 'II', meaning: '回答' },
  { kana: 'せつめいする', kanji: '説明する', class: 'IRR', meaning: '说明' },
  { kana: 'りかいする', kanji: '理解する', class: 'IRR', meaning: '理解' },
  { kana: 'しゅうちゅうする', kanji: '集中する', class: 'IRR', meaning: '集中' },
  { kana: 'ちゅういする', kanji: '注意する', class: 'IRR', meaning: '注意' },
  { kana: 'きをつける', kanji: '気を付ける', class: 'II', meaning: '小心' },
  { kana: 'しごとをする', kanji: '仕事をする', class: 'IRR', meaning: '工作' },
  { kana: 'かいしゃにいく', kanji: '会社に行く', class: 'I', meaning: '上班' },
  { kana: 'かいぎをする', kanji: '会議をする', class: 'IRR', meaning: '开会' },
  { kana: 'ほうこくする', kanji: '報告する', class: 'IRR', meaning: '报告' },
  { kana: 'そうだんする', kanji: '相談する', class: 'IRR', meaning: '商量' },
  { kana: 'けっていする', kanji: '決定する', class: 'IRR', meaning: '决定' },
  { kana: 'せんたくする', kanji: '選択する', class: 'IRR', meaning: '选择' },
  { kana: 'はんだんする', kanji: '判断する', class: 'IRR', meaning: '判断' },
  { kana: 'ひょうかする', kanji: '評価する', class: 'IRR', meaning: '评价' },
  { kana: 'かんりする', kanji: '管理する', class: 'IRR', meaning: '管理' },
  { kana: 'うんえいする', kanji: '運営する', class: 'IRR', meaning: '运营' },
  { kana: 'けいえいする', kanji: '経営する', class: 'IRR', meaning: '经营' },
  { kana: 'はんばいする', kanji: '販売する', class: 'IRR', meaning: '销售' },
  { kana: 'こうにゅうする', kanji: '購入する', class: 'IRR', meaning: '购买' },
  { kana: 'ちゅうもんする', kanji: '注文する', class: 'IRR', meaning: '订购' },
  { kana: 'はいたつする', kanji: '配達する', class: 'IRR', meaning: '配送' },
  { kana: 'うけとる', kanji: '受け取る', class: 'I', meaning: '接收' },
  { kana: 'おくる', kanji: '送る', class: 'I', meaning: '发送' },
  { kana: 'とどく', kanji: '届く', class: 'I', meaning: '到达' },
  { kana: 'とどける', kanji: '届ける', class: 'II', meaning: '送达' },
  { kana: 'れんらくする', kanji: '連絡する', class: 'IRR', meaning: '联系' },
  { kana: 'つうちする', kanji: '通知する', class: 'IRR', meaning: '通知' },
  { kana: 'ほうこくする', kanji: '報告する', class: 'IRR', meaning: '报告' },
  { kana: 'かくにんする', kanji: '確認する', class: 'IRR', meaning: '确认' },
  { kana: 'しょうかいする', kanji: '紹介する', class: 'IRR', meaning: '介绍' },
  { kana: 'あんないする', kanji: '案内する', class: 'IRR', meaning: '引导' },
  { kana: 'てつだう', kanji: '手伝う', class: 'I', meaning: '帮助' },
  { kana: 'きょうりょくする', kanji: '協力する', class: 'IRR', meaning: '合作' },
  { kana: 'さんかする', kanji: '参加する', class: 'IRR', meaning: '参加' },
  { kana: 'しゅっせきする', kanji: '出席する', class: 'IRR', meaning: '出席' },
  { kana: 'けっせきする', kanji: '欠席する', class: 'IRR', meaning: '缺席' },
  { kana: 'ちこくする', kanji: '遅刻する', class: 'IRR', meaning: '迟到' },
  { kana: 'そうたいする', kanji: '早退する', class: 'IRR', meaning: '早退' },
  { kana: 'やすみをとる', kanji: '休みを取る', class: 'I', meaning: '请假' },
  { kana: 'しゅっきんする', kanji: '出勤する', class: 'IRR', meaning: '上班' },
  { kana: 'たいきんする', kanji: '退勤する', class: 'IRR', meaning: '下班' },
  { kana: 'ざんぎょうする', kanji: '残業する', class: 'IRR', meaning: '加班' },
  { kana: 'しゅっちょうする', kanji: '出張する', class: 'IRR', meaning: '出差' },
  { kana: 'てんきんする', kanji: '転勤する', class: 'IRR', meaning: '调动' },
  { kana: 'しょうしんする', kanji: '昇進する', class: 'IRR', meaning: '升职' },
  { kana: 'たいしょくする', kanji: '退職する', class: 'IRR', meaning: '辞职' },
  { kana: 'しゅうしょくする', kanji: '就職する', class: 'IRR', meaning: '就业' },
  { kana: 'めんせつをうける', kanji: '面接を受ける', class: 'II', meaning: '面试' },
  { kana: 'おうぼする', kanji: '応募する', class: 'IRR', meaning: '应聘' },
  { kana: 'さいようする', kanji: '採用する', class: 'IRR', meaning: '录用' },
  { kana: 'きゅうりょうをもらう', kanji: '給料をもらう', class: 'I', meaning: '领工资' },
  { kana: 'ちょきんする', kanji: '貯金する', class: 'IRR', meaning: '存钱' },
  { kana: 'ひきだす', kanji: '引き出す', class: 'I', meaning: '取钱' },
  { kana: 'ふりこむ', kanji: '振り込む', class: 'I', meaning: '转账' },
  { kana: 'しはらう', kanji: '支払う', class: 'I', meaning: '支付' },
  { kana: 'けいさんする', kanji: '計算する', class: 'IRR', meaning: '计算' },
  { kana: 'かぞえる', kanji: '数える', class: 'II', meaning: '数' },
  { kana: 'はかる', kanji: '測る', class: 'I', meaning: '测量' },
  { kana: 'くらべる', kanji: '比べる', class: 'II', meaning: '比较' },
  { kana: 'えらぶ', kanji: '選ぶ', class: 'I', meaning: '选择' },
  { kana: 'きめる', kanji: '決める', class: 'II', meaning: '决定' },
  { kana: 'かんがえる', kanji: '考える', class: 'II', meaning: '思考' },
  { kana: 'おもう', kanji: '思う', class: 'I', meaning: '认为' },
  { kana: 'しんじる', kanji: '信じる', class: 'II', meaning: '相信' },
  { kana: 'うたがう', kanji: '疑う', class: 'I', meaning: '怀疑' },
  { kana: 'きたいする', kanji: '期待する', class: 'IRR', meaning: '期待' },
  { kana: 'のぞむ', kanji: '望む', class: 'I', meaning: '希望' },
  { kana: 'ゆめをみる', kanji: '夢を見る', class: 'II', meaning: '做梦' },
  { kana: 'きぼうする', kanji: '希望する', class: 'IRR', meaning: '希望' },
  { kana: 'ねがう', kanji: '願う', class: 'I', meaning: '祈愿' },
  { kana: 'いのる', kanji: '祈る', class: 'I', meaning: '祈祷' },
  { kana: 'おいわいする', kanji: 'お祝いする', class: 'IRR', meaning: '庆祝' },
  { kana: 'かんしゃする', kanji: '感謝する', class: 'IRR', meaning: '感谢' },
  { kana: 'あやまる', kanji: '謝る', class: 'I', meaning: '道歉' },
  { kana: 'ゆるす', kanji: '許す', class: 'I', meaning: '原谅' },
  { kana: 'はんせいする', kanji: '反省する', class: 'IRR', meaning: '反省' },
  { kana: 'こうかいする', kanji: '後悔する', class: 'IRR', meaning: '后悔' },
  { kana: 'まんぞくする', kanji: '満足する', class: 'IRR', meaning: '满足' },
  { kana: 'ふまんをもつ', kanji: '不満を持つ', class: 'I', meaning: '不满' },
  { kana: 'かんどうする', kanji: '感動する', class: 'IRR', meaning: '感动' },
  { kana: 'きょうみをもつ', kanji: '興味を持つ', class: 'I', meaning: '感兴趣' },
  { kana: 'しゅみをもつ', kanji: '趣味を持つ', class: 'I', meaning: '有爱好' },
  { kana: 'たいけんする', kanji: '体験する', class: 'IRR', meaning: '体验' },
  { kana: 'けいけんする', kanji: '経験する', class: 'IRR', meaning: '经历' },
  { kana: 'はっけんする', kanji: '発見する', class: 'IRR', meaning: '发现' },
  { kana: 'はつめいする', kanji: '発明する', class: 'IRR', meaning: '发明' },
  { kana: 'そうぞうする', kanji: '想像する', class: 'IRR', meaning: '想象' },
  { kana: 'そうさくする', kanji: '創作する', class: 'IRR', meaning: '创作' },
  { kana: 'せいさくする', kanji: '制作する', class: 'IRR', meaning: '制作' },
  { kana: 'せっけいする', kanji: '設計する', class: 'IRR', meaning: '设计' },
  { kana: 'けんせつする', kanji: '建設する', class: 'IRR', meaning: '建设' },
  { kana: 'しゅうりする', kanji: '修理する', class: 'IRR', meaning: '修理' },
  { kana: 'こわす', kanji: '壊す', class: 'I', meaning: '破坏' },
  { kana: 'こわれる', kanji: '壊れる', class: 'II', meaning: '坏了' },
  { kana: 'なおす', kanji: '直す', class: 'I', meaning: '修理' },
  { kana: 'なおる', kanji: '直る', class: 'I', meaning: '修好' },
  { kana: 'つかう', kanji: '使う', class: 'I', meaning: '使用' },
  { kana: 'りようする', kanji: '利用する', class: 'IRR', meaning: '利用' },
  { kana: 'そうさする', kanji: '操作する', class: 'IRR', meaning: '操作' },
  { kana: 'あつかう', kanji: '扱う', class: 'I', meaning: '处理' },
  { kana: 'しょりする', kanji: '処理する', class: 'IRR', meaning: '处理' },
  { kana: 'かいけつする', kanji: '解決する', class: 'IRR', meaning: '解决' },
  { kana: 'かいせつする', kanji: '解説する', class: 'IRR', meaning: '解说' },
  { kana: 'ぶんせきする', kanji: '分析する', class: 'IRR', meaning: '分析' },
  { kana: 'けんとうする', kanji: '検討する', class: 'IRR', meaning: '检讨' },
  { kana: 'ていあんする', kanji: '提案する', class: 'IRR', meaning: '提案' },
  { kana: 'ていしゅつする', kanji: '提出する', class: 'IRR', meaning: '提交' },
  { kana: 'しんせいする', kanji: '申請する', class: 'IRR', meaning: '申请' },
  { kana: 'きょかする', kanji: '許可する', class: 'IRR', meaning: '许可' },
  { kana: 'きんしする', kanji: '禁止する', class: 'IRR', meaning: '禁止' },
  { kana: 'せいげんする', kanji: '制限する', class: 'IRR', meaning: '限制' },
  { kana: 'きそくをまもる', kanji: '規則を守る', class: 'I', meaning: '遵守规则' },
  { kana: 'やくそくをまもる', kanji: '約束を守る', class: 'I', meaning: '遵守约定' },
  { kana: 'じかんをまもる', kanji: '時間を守る', class: 'I', meaning: '守时' },
  { kana: 'ほうりつをまもる', kanji: '法律を守る', class: 'I', meaning: '遵守法律' },
  { kana: 'はんざいをする', kanji: '犯罪をする', class: 'IRR', meaning: '犯罪' },
  { kana: 'つかまる', kanji: '捕まる', class: 'I', meaning: '被抓' },
  { kana: 'つかまえる', kanji: '捕まえる', class: 'II', meaning: '抓住' },
  { kana: 'にげる', kanji: '逃げる', class: 'II', meaning: '逃跑' },
  { kana: 'おいかける', kanji: '追いかける', class: 'II', meaning: '追赶' },
  { kana: 'たたかう', kanji: '戦う', class: 'I', meaning: '战斗' },
  { kana: 'まける', kanji: '負ける', class: 'II', meaning: '败' },
  { kana: 'かつ', kanji: '勝つ', class: 'I', meaning: '胜' },
  { kana: 'きょうそうする', kanji: '競争する', class: 'IRR', meaning: '竞争' },
  { kana: 'しあいをする', kanji: '試合をする', class: 'IRR', meaning: '比赛' },
  { kana: 'うんどうする', kanji: '運動する', class: 'IRR', meaning: '运动' },
  { kana: 'スポーツをする', kanji: 'スポーツをする', class: 'IRR', meaning: '做运动' },
  { kana: 'やきゅうをする', kanji: '野球をする', class: 'IRR', meaning: '打棒球' },
  { kana: 'サッカーをする', kanji: 'サッカーをする', class: 'IRR', meaning: '踢足球' },
  { kana: 'テニスをする', kanji: 'テニスをする', class: 'IRR', meaning: '打网球' },
  { kana: 'バスケットボールをする', kanji: 'バスケットボールをする', class: 'IRR', meaning: '打篮球' },
  { kana: 'バレーボールをする', kanji: 'バレーボールをする', class: 'IRR', meaning: '打排球' },
  { kana: 'ゴルフをする', kanji: 'ゴルフをする', class: 'IRR', meaning: '打高尔夫' },
  { kana: 'スキーをする', kanji: 'スキーをする', class: 'IRR', meaning: '滑雪' },
  { kana: 'スケートをする', kanji: 'スケートをする', class: 'IRR', meaning: '滑冰' },
  { kana: 'じょぎんぐをする', kanji: 'ジョギングをする', class: 'IRR', meaning: '慢跑' },
  { kana: 'さいくりんぐをする', kanji: 'サイクリングをする', class: 'IRR', meaning: '骑自行车' },
  { kana: 'ハイキングをする', kanji: 'ハイキングをする', class: 'IRR', meaning: '徒步旅行' },
  { kana: 'キャンプをする', kanji: 'キャンプをする', class: 'IRR', meaning: '露营' },
  { kana: 'つりをする', kanji: '釣りをする', class: 'IRR', meaning: '钓鱼' },
  { kana: 'しゃしんをとる', kanji: '写真を撮る', class: 'I', meaning: '拍照' },
  { kana: 'えいがをみる', kanji: '映画を見る', class: 'II', meaning: '看电影' },
  { kana: 'テレビをみる', kanji: 'テレビを見る', class: 'II', meaning: '看电视' },
  { kana: 'おんがくをきく', kanji: '音楽を聞く', class: 'I', meaning: '听音乐' },
  { kana: 'ラジオをきく', kanji: 'ラジオを聞く', class: 'I', meaning: '听收音机' },
  { kana: 'ほんをよむ', kanji: '本を読む', class: 'I', meaning: '读书' },
  { kana: 'しんぶんをよむ', kanji: '新聞を読む', class: 'I', meaning: '读报纸' },
  { kana: 'ざっしをよむ', kanji: '雑誌を読む', class: 'I', meaning: '读杂志' },
  { kana: 'インターネットをする', kanji: 'インターネットをする', class: 'IRR', meaning: '上网' },
  { kana: 'コンピューターをつかう', kanji: 'コンピューターを使う', class: 'I', meaning: '使用电脑' },
  { kana: 'けいたいでんわをつかう', kanji: '携帯電話を使う', class: 'I', meaning: '使用手机' },
  { kana: 'アプリをつかう', kanji: 'アプリを使う', class: 'I', meaning: '使用应用' },
  { kana: 'ゲームをする', kanji: 'ゲームをする', class: 'IRR', meaning: '玩游戏' },
  { kana: 'パーティーをする', kanji: 'パーティーをする', class: 'IRR', meaning: '开派对' },
  { kana: 'おまつりにいく', kanji: 'お祭りに行く', class: 'I', meaning: '参加节日' },
  { kana: 'コンサートにいく', kanji: 'コンサートに行く', class: 'I', meaning: '听音乐会' },
  { kana: 'びじゅつかんにいく', kanji: '美術館に行く', class: 'I', meaning: '去美术馆' },
  { kana: 'はくぶつかんにいく', kanji: '博物館に行く', class: 'I', meaning: '去博物馆' },
  { kana: 'どうぶつえんにいく', kanji: '動物園に行く', class: 'I', meaning: '去动物园' },
  { kana: 'すいぞくかんにいく', kanji: '水族館に行く', class: 'I', meaning: '去水族馆' },
  { kana: 'こうえんにいく', kanji: '公園に行く', class: 'I', meaning: '去公园' },
  { kana: 'うみにいく', kanji: '海に行く', class: 'I', meaning: '去海边' },
  { kana: 'やまにいく', kanji: '山に行く', class: 'I', meaning: '去山里' },
  { kana: 'おんせんにいく', kanji: '温泉に行く', class: 'I', meaning: '去温泉' },
  { kana: 'ホテルにとまる', kanji: 'ホテルに泊まる', class: 'I', meaning: '住酒店' },
  { kana: 'りょかんにとまる', kanji: '旅館に泊まる', class: 'I', meaning: '住旅馆' },
  { kana: 'みんしゅくにとまる', kanji: '民宿に泊まる', class: 'I', meaning: '住民宿' },
  { kana: 'ユースホステルにとまる', kanji: 'ユースホステルに泊まる', class: 'I', meaning: '住青年旅社' },
  { kana: 'テントでねる', kanji: 'テントで寝る', class: 'II', meaning: '在帐篷里睡觉' },
  { kana: 'よやくをとる', kanji: '予約を取る', class: 'I', meaning: '预订' },
  { kana: 'チェックインする', kanji: 'チェックインする', class: 'IRR', meaning: '办理入住' },
  { kana: 'チェックアウトする', kanji: 'チェックアウトする', class: 'IRR', meaning: '办理退房' },
  { kana: 'かぎをかりる', kanji: '鍵を借りる', class: 'II', meaning: '借钥匙' },
  { kana: 'かぎをかえす', kanji: '鍵を返す', class: 'I', meaning: '还钥匙' },
  { kana: 'りょうきんをはらう', kanji: '料金を払う', class: 'I', meaning: '付费用' },
  { kana: 'レシートをもらう', kanji: 'レシートをもらう', class: 'I', meaning: '拿收据' },
  { kana: 'おつりをもらう', kanji: 'お釣りをもらう', class: 'I', meaning: '找零钱' },
  { kana: 'クレジットカードではらう', kanji: 'クレジットカードで払う', class: 'I', meaning: '用信用卡付款' },
  { kana: 'げんきんではらう', kanji: '現金で払う', class: 'I', meaning: '用现金付款' },
  { kana: 'でんしマネーではらう', kanji: '電子マネーで払う', class: 'I', meaning: '用电子货币付款' },
  { kana: 'ポイントをつかう', kanji: 'ポイントを使う', class: 'I', meaning: '使用积分' },
  { kana: 'クーポンをつかう', kanji: 'クーポンを使う', class: 'I', meaning: '使用优惠券' },
  { kana: 'わりびきをうける', kanji: '割引を受ける', class: 'II', meaning: '享受折扣' },
  { kana: 'セールでかう', kanji: 'セールで買う', class: 'I', meaning: '在促销时购买' },
  { kana: 'オンラインでかう', kanji: 'オンラインで買う', class: 'I', meaning: '网上购买' },
  { kana: 'はいそうしてもらう', kanji: '配送してもらう', class: 'I', meaning: '请配送' },
  { kana: 'とりにいく', kanji: '取りに行く', class: 'I', meaning: '去取' },
  { kana: 'へんぴんする', kanji: '返品する', class: 'IRR', meaning: '退货' },
  { kana: 'こうかんする', kanji: '交換する', class: 'IRR', meaning: '交换' },
  { kana: 'しゅうりをたのむ', kanji: '修理を頼む', class: 'I', meaning: '请求修理' },
  { kana: 'ほしょうをうける', kanji: '保証を受ける', class: 'II', meaning: '享受保修' },
  { kana: 'サービスをうける', kanji: 'サービスを受ける', class: 'II', meaning: '接受服务' },
  { kana: 'もんくをいう', kanji: '文句を言う', class: 'I', meaning: '抱怨' },
  { kana: 'くじょうする', kanji: '苦情する', class: 'IRR', meaning: '投诉' },
  { kana: 'かんしゃのきもちをつたえる', kanji: '感謝の気持ちを伝える', class: 'II', meaning: '表达感谢' },
  { kana: 'ひょうかする', kanji: '評価する', class: 'IRR', meaning: '评价' },
  { kana: 'レビューをかく', kanji: 'レビューを書く', class: 'I', meaning: '写评论' },
  { kana: 'おすすめする', kanji: 'お勧めする', class: 'IRR', meaning: '推荐' },
  { kana: 'しょうかいする', kanji: '紹介する', class: 'IRR', meaning: '介绍' },
  { kana: 'ともだちをつくる', kanji: '友達を作る', class: 'I', meaning: '交朋友' },
  { kana: 'なかよくなる', kanji: '仲良くなる', class: 'I', meaning: '变亲密' },
  { kana: 'けんかする', kanji: '喧嘩する', class: 'IRR', meaning: '吵架' },
  { kana: 'なかなおりする', kanji: '仲直りする', class: 'IRR', meaning: '和好' },
  { kana: 'わかれる', kanji: '別れる', class: 'II', meaning: '分手' },
  { kana: 'さよならをいう', kanji: 'さよならを言う', class: 'I', meaning: '告别' },
  { kana: 'また会う', kanji: 'また会う', class: 'I', meaning: '再见面' },
  { kana: 'れんらくをとる', kanji: '連絡を取る', class: 'I', meaning: '保持联系' },
  { kana: 'おもいでをつくる', kanji: '思い出を作る', class: 'I', meaning: '制造回忆' },
  { kana: 'おもいです', kanji: '思い出す', class: 'I', meaning: '回忆起' },
  { kana: 'なつかしがる', kanji: '懐かしがる', class: 'I', meaning: '怀念' },
  { kana: 'みらいをかんがえる', kanji: '未来を考える', class: 'II', meaning: '考虑未来' },
  { kana: 'ゆめをもつ', kanji: '夢を持つ', class: 'I', meaning: '有梦想' },
  { kana: 'もくひょうをたてる', kanji: '目標を立てる', class: 'II', meaning: '设定目标' },
  { kana: 'けいかくをたてる', kanji: '計画を立てる', class: 'II', meaning: '制定计划' },
  { kana: 'じっこうする', kanji: '実行する', class: 'IRR', meaning: '执行' },
  { kana: 'たっせいする', kanji: '達成する', class: 'IRR', meaning: '达成' },
  { kana: 'せいちょうする', kanji: '成長する', class: 'IRR', meaning: '成长' },
  { kana: 'しんぽする', kanji: '進歩する', class: 'III', meaning: '进步' },
  { kana: 'はってんする', kanji: '発展する', class: 'IRR', meaning: '发展' },
  { kana: 'こうじょうする', kanji: '向上する', class: 'IRR', meaning: '提高' },
  { kana: 'かいぜんする', kanji: '改善する', class: 'IRR', meaning: '改善' },
  { kana: 'へんかする', kanji: '変化する', class: 'IRR', meaning: '变化' },
  { kana: 'てきおうする', kanji: '適応する', class: 'IRR', meaning: '适应' },
  { kana: 'ちょうせいする', kanji: '調整する', class: 'IRR', meaning: '调整' },
  { kana: 'バランスをとる', kanji: 'バランスを取る', class: 'I', meaning: '保持平衡' },
  { kana: 'あんていする', kanji: '安定する', class: 'IRR', meaning: '稳定' },
  { kana: 'ふあんていになる', kanji: '不安定になる', class: 'I', meaning: '变不稳定' },
  { kana: 'きけんになる', kanji: '危険になる', class: 'I', meaning: '变危险' },
  { kana: 'あんぜんになる', kanji: '安全になる', class: 'I', meaning: '变安全' },
  { kana: 'けんこうになる', kanji: '健康になる', class: 'I', meaning: '变健康' },
  { kana: 'びょうきになる', kanji: '病気になる', class: 'I', meaning: '生病' },
  { kana: 'つかれる', kanji: '疲れる', class: 'II', meaning: '疲劳' },
  { kana: 'げんきになる', kanji: '元気になる', class: 'I', meaning: '恢复精神' },
  { kana: 'きぶんがよくなる', kanji: '気分が良くなる', class: 'I', meaning: '心情变好' },
  { kana: 'きぶんがわるくなる', kanji: '気分が悪くなる', class: 'I', meaning: '心情变坏' },
  { kana: 'きもちがよくなる', kanji: '気持ちが良くなる', class: 'I', meaning: '感觉变好' },
  { kana: 'きもちがわるくなる', kanji: '気持ちが悪くなる', class: 'I', meaning: '感觉变坏' },
  { kana: 'らくになる', kanji: '楽になる', class: 'I', meaning: '变轻松' },
  { kana: 'くるしくなる', kanji: '苦しくなる', class: 'I', meaning: '变痛苦' },
  { kana: 'たのしくなる', kanji: '楽しくなる', class: 'I', meaning: '变快乐' },
  { kana: 'つまらなくなる', kanji: 'つまらなくなる', class: 'I', meaning: '变无聊' },
  { kana: 'おもしろくなる', kanji: '面白くなる', class: 'I', meaning: '变有趣' },
  { kana: 'つまらなくなる', kanji: 'つまらなくなる', class: 'I', meaning: '变无聊' },
  { kana: 'むずかしくなる', kanji: '難しくなる', class: 'I', meaning: '变困难' },
  { kana: 'やさしくなる', kanji: '易しくなる', class: 'I', meaning: '变容易' },
  { kana: 'かんたんになる', kanji: '簡単になる', class: 'I', meaning: '变简单' },
  { kana: 'ふくざつになる', kanji: '複雑になる', class: 'I', meaning: '变复杂' },
  { kana: 'べんりになる', kanji: '便利になる', class: 'I', meaning: '变方便' }
];

async function seedVerbs() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
  });

  try {
    // 检查现有数据量
    const { rows } = await pool.query('SELECT COUNT(*) FROM verbs');
    const count = parseInt(rows[0].count);
    
    console.log(`动词表当前有 ${count} 条数据`);
    
    // 过滤出尚未存在的动词
    const existingVerbs = await pool.query('SELECT kana FROM verbs');
    const existingKanaSet = new Set(existingVerbs.rows.map(row => row.kana));
    const newVerbs = verbsData.filter(verb => !existingKanaSet.has(verb.kana));
    
    if (newVerbs.length === 0) {
      console.log('所有动词已存在，无需导入新数据');
      return;
    }
    
    console.log(`准备导入 ${newVerbs.length} 个新动词...`);

    console.log('开始导入动词种子数据...');
    
    // 批量插入新动词数据
    for (let i = 0; i < newVerbs.length; i += 100) {
      const batch = newVerbs.slice(i, i + 100);
      const values = batch.map((verb, index) => 
        `($${index * 4 + 1}, $${index * 4 + 2}, $${index * 4 + 3}, $${index * 4 + 4})`
      ).join(', ');
      
      const params = batch.flatMap(verb => [verb.kana, verb.kanji, verb.class, verb.meaning]);
      
      await pool.query(
        `INSERT INTO verbs (kana, kanji, group_type, meaning) VALUES ${values}`,
        params
      );
      
      console.log(`已导入 ${Math.min(i + 100, verbsData.length)} / ${verbsData.length} 个动词`);
    }
    
    console.log(`成功导入 ${verbsData.length} 个动词到数据库`);
  } catch (error) {
    console.error('导入动词数据时出错:', error);
  } finally {
    await pool.end();
  }
}

// 如果直接运行此文件
if (require.main === module) {
  seedVerbs();
}

module.exports = { seedVerbs, verbsData };